[platformio]
default_envs = esp32dev
core_dir = .pio-core

[env]
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -Wall -Wextra
test_framework = unity

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = adafruit/Adafruit NeoPixel@1.12.5
test_ignore = *

[env:native]
platform = native@1.2.1
test_build_src = yes
build_src_filter = +<core/>
build_flags = ${env.build_flags} -O0 -g --coverage
extra_scripts = pre:scripts/native.py
